os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=x86_64 DISTRIB=alpine
#    - ARCH=armhf DISTRIB=debian
#    - ARCH=armhf DISTRIB=alpine
  global:
  - secure: gAXzHa1eE8WMQ9UFX/fiPwZTzTbXGVEpgG7sRGWmVxkgadTXN+K1fZfqy8i4F3kaAG8t/PzHY1Eubf2GUGX1VnxmUGcd/5xkdWM4j9LMerg+k6vEypa4rmQuFSXbkIJvc0GvvgtaQDxYcTdjpnXZ5Exv+iQBC2yv7LSIY8tZBz1SwFoIlGs34+r/GMGvkfwPSshGNdv5UzpjmUECgcP060nXEtC/C16s+U0xnADtEznhqo7q9DrYZahZ7xSNX6vj+SZUcNifyaIjTGsLOXL/eAlWh1vMBKSIADeyQpxAETYlh+e71rTokN9SszzRSaTM0kytFba5k7XSx50wq46RzuYXpK7uHPpYCrv0GO3RS7LJMVhZw/4LGvVwwCIjAfhIkIu/S6O/Fqq79y4Dlk+0/6OokbQBj3LN5XfuJPQm/xuAEG7jjR9WPwqwMAgzRN2INAVDUUWIPpVnFUQXYaLaF5FBIFY3My30JkrYizRoSPOxmY1LWQlTdQCcxotquhhrUTutSmF5keZXfb4LPWMD93v6b0U6HL3kxHfm7/f83AUyZhpVAPNt415Vly7I7DHxgfTuV+liPNxPfaxI+cSt6ucJ0RoLl894vRFdY3Zk3OKTqsWguZFZ7Laqf501oqEwwa8wwnpXIWZPMfxno3AT6wFSOqv3QuqbC9DJiT53gVA=
  - secure: fFpjBI2b3HwhMzEhs3r9EjxNLf89N+AeavLL7LbzPkmYqSjClpFy35X9mqZljkj5+jLlzd1InFwGIt5Ju/VW60Gnm6rWxSiWszuXlcAV5oXjAYVcCPsdWOGbKPaudGvG5C6Ta9XDEgXyqyh1hOWOhnbFTLN8+HsNHgHXzmeAp82mXNzt6u+b1jaw71O1O0UyrsA+tprnqzEdXrPCJ9qyGgtvlhHmPiDN3ZMwsrpKgYbvhVl6NBfq1iWXhOI2+K255u7fBpFi+k8atOOA49zuTfYFblfTjE8FdUWA7cLm/0Ofj9AEx2C4SGKnFVPjF0VOVDYTakCLYh/6KkKSvU2Ud2zmUFCzD7STxALBFDaFp38zw4DC9kQqqrBQfUcb1wCP53NFNNx360j4BOsuxM1BskDHAF83JQc43r1LzFU3n78WyBf9PusmhkaxaJTm5xOytHMiIXfeV70K3R8L+Uav0YOZUMZDmDJsI9/fHjzuYfhxRoDzjo6nOXdQr3oJT1Mk7EoZpV4OgevJY7Xokw3ByzSYhC0DEg1UcDsT/CckU4XKyDggCumUFiWNvNR9MzyCw2ahh9/INZpDhWajpD5+kzTv3YclMwPYI+v8Ae+cSUW/N7TrRivGV3bozmwdrV+rt0L0CLckbX/IZDKK2yt4GRTVNHmTurWJTBVuTlg2qxU=
  - secure: PWDQKOxPXZXJ2vAUVmMi1esoA8fkbsB/NGBU+6DAoYhfEW5jCT9QxwOrORUqSe7fbS/omyzOkU0kRJSd35C+SDugwU/WLNZnqRXdrws+jw4iNowjsOJMVZRVPg9bCYtx8mI4dvycyi+M1nsl306Kfz1lawuJHGoL+JvtIO2R6FEEhw47jbnOnxSZ2Rpv+Jx7Gy4zjmNb4QvElIFHqvMKaQcCObn5BQ8TcB9UVkNknkUMZNkf1ChmulbT/Cccxmg+cCSnaieF+0Y6N4s7L5baeqaTrjOpvJ6AClGTM6MnWu8Mmlf2q0EJrwwuRC2a45xrW+wmShAEYjAHu7MOSpM1QlMo8FoXOq5TOiGgorlSHoBy3bqe46WQujks1nfJ7DPEGOahbWdZ6QrXTj88HcImDy4QuswWNqLDzh/pW5Y7QMOdA4OBoeMTjC7lOmP7kIaePXARv96P377pPMymKYLP7CV/2ivVn/XF6h0u59xeXq96hanRnweNv8EAc8PDNRxnBEERxZi9EY+/K0koTqBPViyKhDNZacjMqLYEgQqN5Se/lu25q29TBspTNTJ/FhrjYoCruqO/5y+ogE1oWtTvwC7m1sJM0nHvhiKyojMVYNWLZqLRSTTPDbm18d1o0k5G9ZOkw/bqCigxZslAtZ7X+owdQ7S8J7p+2wvzQBnkj7I=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
